services:
  - type: web
    name: jeweller-app
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      echo "Installing frontend dependencies..."
      npm install
      echo "Building frontend..."
      npm run build:frontend
      echo "Installing server dependencies..."
      cd server && pwd && npm install
      echo "Listing server directory..."
      ls -la
      echo "Checking node_modules..."
      ls -la node_modules | head -10
      echo "Making start script executable..."
      chmod +x ../start.sh
    startCommand: bash start.sh
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: jeweller-app
          property: port
    disk:
      name: uploads
      mountPath: /opt/render/project/src/server/uploads
      sizeGB: 1 