services:
  - type: web
    name: jeweller-app
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      npm install
      npm run build:frontend
      cd server
      npm install --production
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: jeweller-app
          property: port
    disk:
      name: uploads
      mountPath: /opt/render/project/src/server/uploads
      sizeGB: 1 